### PR TITLE
BDD: get single user test.

### PR DESCRIPTION
**Pull request by sergiitk**
Add mocha test for unauthorized call to Northstar to get single user.
This is to spec `NorthstarClient.getUser(type, id)` method and  `NorthstarUser` class.

```
  ․․․

  1 passing (5ms)
  2 pending
```

CC @DFurnes Mind giving this a quick look?

### CODE REVIEW

**Comment by DFurnes** [comment]
Looks nice to me! 👍

**Comment by deezone** [comment]
```
[~/Sites/message-broker/northstar-js] $ npm test

> northstar-js@0.0.1 test /Users/darrenlee/Sites/message-broker/northstar-js
> npm run lint && mocha


> northstar-js@0.0.1 lint /Users/darrenlee/Sites/message-broker/northstar-js
> eslint test/*.js lib/*.js

/Users/darrenlee/Sites/message-broker/northstar-js/test/northstar-client.test.js:6
const NorthstarClient = require('../lib/northstar-client');
^^^^^
SyntaxError: Use of const in strict mode.
```

**Comment by sergiitk** [comment]
@DeeZone I believe you're running outdated Node.js. Please make sure you have at least v4.4: https://github.com/DoSomething/northstar-js/blob/master/package.json#L6

**Comment by deezone** [comment]
👍

**Comment by deezone** [comment]
My bad:

```
$ node -v
v4.4.0

$ npm test

> northstar-js@0.0.1 test /Users/deelee/Documents/Projects/DoSomething/northstar-js
> npm run lint && mocha


> northstar-js@0.0.1 lint /Users/deelee/Documents/Projects/DoSomething/northstar-js
> eslint test/*.js lib/*.js



  ․

  1 passing (5ms)
```

**Pull request merged**
